/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PravidlaRouteImport } from './routes/pravidla'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GCodeRouteImport } from './routes/g.$code'

const PravidlaRoute = PravidlaRouteImport.update({
  id: '/pravidla',
  path: '/pravidla',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GCodeRoute = GCodeRouteImport.update({
  id: '/g/$code',
  path: '/g/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pravidla': typeof PravidlaRoute
  '/g/$code': typeof GCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pravidla': typeof PravidlaRoute
  '/g/$code': typeof GCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pravidla': typeof PravidlaRoute
  '/g/$code': typeof GCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pravidla' | '/g/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pravidla' | '/g/$code'
  id: '__root__' | '/' | '/pravidla' | '/g/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PravidlaRoute: typeof PravidlaRoute
  GCodeRoute: typeof GCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pravidla': {
      id: '/pravidla'
      path: '/pravidla'
      fullPath: '/pravidla'
      preLoaderRoute: typeof PravidlaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g/$code': {
      id: '/g/$code'
      path: '/g/$code'
      fullPath: '/g/$code'
      preLoaderRoute: typeof GCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PravidlaRoute: PravidlaRoute,
  GCodeRoute: GCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
